### ISSUE TITLE
How to display the current fan speed?

### ISSUE THREAD

**Issue by GeerGuy** [hunterjm/ac-infinity-hacs#14]
Is it possible to display the current fan speed without having to open up the fan window?

There are sensors for the humidity and the temperature, but not for the fan speed.

**Comment by flamedodger** [comment]
> Is it possible to display the current fan speed without having to open up the fan window?
> 
> There are sensors for the humidity and the temperature, but not for the fan speed.

I use a slider button card, it shows the fan percentage and has a revolving fan icon.
